spring.application.name=data-p1
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
#MS
spring.jpa.properties.jakarta.persistence.query.timeout=2000
#SEG
#POOL CONECTIONS
spring.datasource.hikari.connection-timeout=3000
#logging.level.root=debug
#spring.jpa.defer-datasource-initialization=true