# R1: Puerto personalizado segun el examen
server.port=9090

# Nombre de la aplicacion
spring.application.name=cowork-api

# Tamano maximo de archivos para multipart (subida de comprobantes PDF)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
